### Que1. Discuss string slicing and provide examples.

String slicing in Python is a way to access a portion or "slice" of a string. Strings in Python are sequences of characters, and each character in a string has an index number. The first character has an index of 0, the second has an index of 1, and so on. Negative indices can be used to start counting from the end of the string, where -1 is the last character.

##### Description: 
Characters arranged in an unchangeable order. Consider writing a sentence, a paragraph, or a piece of material.

##### Operations: 
Each character in the string can be accessed by its index, or position. Substrings can be extracted using slicing. Strings can be joined together and altered using a variety of techniques 

##### Syntax of String Slicing

The general syntax for string slicing is:

python
string[start:stop:step]


- start: The index at which the slice starts (inclusive). If omitted, it defaults to the beginning of the string.
- stop: The index at which the slice stops (exclusive). If omitted, it defaults to the end of the string.
- step: The interval between each character in the slice. If omitted, it defaults to 1.

#### Examples:


##### Basic Slicing

In [1]:
text = "I am Aalind"

In [2]:
text[0:5] #Slice from index 0 to 5

'I am '

In [3]:
text[5:] # lice from index 7 to the end

'Aalind'

In [4]:
text[:5] #Slice from the beginning to index 5

'I am '

##### Using Negative Indices

In [5]:
text = "I am Aalind"

In [6]:
text[-6:] # Slice the last 6 characters

'Aalind'

In [7]:
text[:-6] #Slice everything except the last character

'I am '

#####  Using Step

In [8]:
text = "I am Aalind" # Slice every second character

In [9]:
text[::2]

'Ia aid'

In [10]:
text[::-1] # Reverse the string

'dnilaA ma I'

##### Omitting Indices

In [11]:
text = "I am Aalind"

In [12]:
text[:] #Full string

'I am Aalind'

In [13]:
text[:5] # Slice from the beginning to index 5, omitting the start

'I am '

In [14]:
text[5:] # Slice from index 7 to the end, omitting the end

'Aalind'

#### Common Uses of String Slicing

- Extracting substrings: You can easily get any part of the string by specifying the desired range of indices.
- Reversing a string: By using a step of -1, you can quickly reverse the string.
- Skipping characters: By using a step greater than 1, you can create a slice that skips characters.

String slicing is a powerful feature in Python that allows for flexible and efficient string manipulation.

### Que2. Explain the key features of lists in python.

Lists in Python are one of the most versatile and commonly used data structures. They are ordered, mutable (i.e., changeable), and can store elements of different data types. Here are the key features of lists in Python:


#### 1. *Ordered Collection*

Lists maintain the order of elements as they were inserted. This means that if you create a list, the elements will remain in the same sequence unless explicitly modified.
   

In [15]:
list_collection = [1,2,3,4,5]
list_collection

[1, 2, 3, 4, 5]

#### 2. Mutable

Lists are mutable, which means you can change, add, or remove elements after the list has been created.

In [16]:
list = ["apple", "grapes","orange"]
list[1] = "mango"

In [17]:
list

['apple', 'mango', 'orange']

#### 3. Dynamic Size

Lists can grow and shrink in size as you add or remove elements. You don’t need to declare the size of a list when you create it.

In [18]:
list = ["apple", "grapes","orange"]
list.append("mango")

In [19]:
list

['apple', 'grapes', 'orange', 'mango']

#### 4. Heterogeneous Elements

A list can contain elements of different data types. You can mix integers, floats, strings, and even other lists within a list.

In [20]:
list = ["apple", "grapes",["orange", "mango"]]

In [21]:
list

['apple', 'grapes', ['orange', 'mango']]

#### 5. Indexed Access

You can access individual elements of a list using their index, starting from 0 for the first element. Negative indexing is also supported, where -1 refers to the last element.

In [22]:
list = ["apple", "grapes","orange"]

In [23]:
list[1]

'grapes'

In [24]:
list[-1]

'orange'

#### 6. Slicing

Lists support slicing, which allows you to access a subset of the list. The syntax is similar to string slicing.

In [25]:
my_list = [10, 20, 30, 40, 50]
my_list[1:4]  

[20, 30, 40]

#### 7. Iteration

You can easily iterate over the elements of a list using loops.

In [26]:
list = ["apple", "grapes","orange"]
for item in list:
    print(item)

apple
grapes
orange


#### 8. Comprehensions

Python provides list comprehensions, which offer a concise way to create lists by iterating over an iterable and optionally applying conditions.

In [27]:
squares = [x**2 for x in range(5)]
print(squares)

[0, 1, 4, 9, 16]


#### 9. Built-in Functions and Methods

 Lists come with many built-in functions and methods that make it easy to manipulate them:

- len(): Returns the number of elements in the list.
- append(): Adds an element to the end of the list.
- extend(): Adds multiple elements to the end of the list.
- insert(): Inserts an element at a specified index.
- remove(): Removes the first occurrence of a specified element.
- pop(): Removes and returns the element at the specified index (or the last element if no index is specified).
- sort(): Sorts the list in place.
- reverse(): Reverses the order of the list in place.
- index(): Returns the index of the first occurrence of a specified element.
- count(): Returns the number of occurrences of a specified element.

#### 10. Nesting

 Lists can contain other lists as elements, which allows for the creation of complex, multi-dimensional data structures.

In [28]:
list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
list[1][2]

6

#### Summary

Lists in Python are powerful and flexible, allowing for easy data storage and manipulation. Their dynamic nature, coupled with a wide range of methods and functionalities, makes them an essential tool for any Python programmer.

### Que3. Describe how to access, modify, and delete elements in a list with examples.

In Python, lists are ordered, mutable collections of elements, which means you can access, modify, and delete elements in a variety of ways. Here are examples of each operation:

#### 1. Accessing Elements in a List

You can access elements in a list using indexing, slicing, or negative indexing.


#### Example list

##### Accessing by index

In [29]:
fruits = ['apple', 'banana', 'mango', 'orange']

In [30]:
fruits[1] 

'banana'

 ##### Accessing with negative indexing 

In [31]:
fruits[-1]

'orange'

##### Accessing a slice

In [32]:
fruits[1:3] 

['banana', 'mango']

#### 2. Modifying Elements in a List

You can modify elements by assigning a new value to a specific index or by using slices to modify multiple values at once.

#### Example list

##### Modifying a single element

In [33]:
fruits = ["apple", "banana", "mango", "orange"]

In [34]:
fruits[1] = "grapes" 

In [35]:
print(fruits)

['apple', 'grapes', 'mango', 'orange']


##### Modifying a slice of elements

In [36]:
fruits = ["apple", "banana", "mango", "orange"]

In [37]:
fruits[1:3] = ["grapes","lichi"] 

In [38]:
print(fruits)

['apple', 'grapes', 'lichi', 'orange']


#### 3. Deleting Elements in a List

You can delete elements using the del statement, remove() method, pop(), or by slicing.

#### Example list

##### Deleting by index

In [39]:
fruits = ["apple", "banana", "mango", "orange"]

In [40]:
del fruits[1] 

In [41]:
print(fruits)

['apple', 'mango', 'orange']


##### Removing an element by value

In [42]:
fruits = ["apple", "banana", "mango", "orange"]

In [43]:
fruits.remove("mango") 

In [44]:
print(fruits)

['apple', 'banana', 'orange']


##### Deleting with pop

In [45]:
popped_element = fruits.pop()

In [46]:
print(fruits) 

['apple', 'banana']


In [47]:
print(popped_element)

orange


##### Deleting a slice

In [48]:
fruits = ["apple", "banana", "mango", "orange"]

In [49]:
del fruits[1:3] 

In [50]:
print(fruits)

['apple', 'orange']


#### Summary:

- Accessing: Use indexing (list[index]) or slicing (list[start:end]).
- Modifying: Assign a new value using an index (list[index] = value) or modify slices.
- Deleting: Use del, remove(), pop(), or slice deletion to remove elements.

### Que4. Compare and contrast tuples and lists with examples.

Both tuples and lists are used to store collections of items in Python, but they have distinct differences in their behavior and use cases. Below is a comparison and contrast of tuples and lists, with examples for clarity.

#### 1. Mutability:

- Lists: Mutable, meaning you can modify, add, or remove elements after creation.
- Tuples: Immutable, meaning once they are created, their elements cannot be modified.


##### Example:

##### List example (Mutable)

In [51]:
fruits_list = ["apple", "banana", "mango", "orange"]

In [52]:
fruits_list[1] = "grapes"

In [53]:
print(fruits_list)

['apple', 'grapes', 'mango', 'orange']


##### Tuple example (Immutable)

In [54]:
fruits_tuple = ("apple", "banana", "mango", "orange")

In [55]:
#fruits_tuple[1] = "grapes" # This will raise an error: TypeError: 'tuple' object does not support item assignment

#### 2. Syntax:

- Lists: Created using square brackets [ ].
- Tuples: Created using parentheses ( ).

##### Example:

In [56]:
# List
my_list = [1, 2, 3]

In [57]:
# Tuple
my_tuple = (1, 2, 3)

#### 3. Performance:

- Lists: Slower than tuples when performing operations because they are mutable.
- Tuples: Faster than lists, especially when dealing with large amounts of data, due to their immutability.

#### 4. Use Cases:

- Lists: Used when you need a dynamic collection of items that can change over time (e.g., adding/removing elements).
- Tuples: Used for fixed collections of items that should not change, such as representing data records, or returning multiple values from a function.

##### Example:

In [58]:
# List - for a collection of items that may change
shopping_list = ["milk", "eggs", "bread"]

In [59]:
shopping_list.append ("butter")

In [60]:
print(shopping_list)

['milk', 'eggs', 'bread', 'butter']


In [61]:
# Tuple - for a collection of fixed items, like coordinates or database records
coordinates = (52.516667, 13.388889)

#### 5. Methods:

- Lists: Have many built-in methods like append(), remove(), pop(), sort(), etc.
- Tuples: Have only two methods: count() and index() because they are immutable.

##### Example:

In [62]:
 # List methods
fruits_list = ["apple", "banana", "mango", "orange"]

In [63]:
fruits_list.append("cherry")  
fruits_list.remove("banana")

In [64]:
print(fruits_list)

['apple', 'mango', 'orange', 'cherry']


In [65]:
# Tuple methods
fruits_list = ["apple", "banana", "mango", "orange"]

In [66]:
fruits_list.count("banana")

1

In [67]:
fruits_list.index("orange")

3

#### 6. Size:

- Lists: Take up more memory since they are dynamic and can be modified.
- Tuples: Take up less memory as they are immutable and fixed in size.

##### Example:

In [68]:
my_list = [1, 2, 3]
my_tuple = (1, 2, 3)

In [69]:
sys.getsizeof(my_list)

88

In [70]:
sys.getsizeof(my_tuple)

64

#### 7. Hashability:

- Lists: Not hashable, so they cannot be used as keys in a dictionary.
- Tuples: Hashable (if all elements inside are hashable), so they can be used as dictionary keys.

##### Example:

In [71]:
# List cannot be used as a dictionary key
# my_dict = {[1, 2, 3]: 'value'}  # TypeError: unhashable type: 'list'

In [72]:
# Tuple can be used as a dictionary key
my_dict = {(1, 2, 3): "value"}

In [73]:
my_dict

{(1, 2, 3): 'value'}

#### 8. Nested Structures:

Both lists and tuples can be nested inside each other, but the same rules of mutability apply.

##### Example:

In [74]:
nested_list = [[1, 2], [3, 4]]
nested_tuple = ((1, 2), (3, 4))

In [75]:
# You can modify nested lists
nested_list[0][0] = 10

In [76]:
nested_list

[[10, 2], [3, 4]]

In [77]:
# You cannot modify elements inside a tuple
# nested_tuple[0][0] = 10  # Raises an error: TypeError: 'tuple' object does not support item assignment

### Que 5.  Describe the key features of sets and provide examples of their use.

In Python, a set is an unordered collection of unique elements. Here are the key features of sets:

#### 1. Unordered Collection: 
Sets do not maintain any particular order of elements, unlike lists or tuples. This means that the position of elements in a set is irrelevant.
   

##### example:

In [78]:
my_set = {3, 1, 4, 2}
print(my_set)  # Output might be: {1, 2, 3, 4} or any other order

{1, 2, 3, 4}


#### 2. Unique Elements:
Sets automatically ensure that all elements are unique. If you add duplicate elements, they will be stored only once.

##### example:

In [79]:
my_set = {1, 2, 2, 3, 4}
print(my_set)  # Output: {1, 2, 3, 4}

{1, 2, 3, 4}


#### 3. Mutable:
Sets can be modified after creation by adding or removing elements. However, the elements themselves must be immutable 

##### example:

In [80]:
my_set = {1, 2, 3}
my_set.add(4)  # Adds 4 to the set
my_set.remove(2)  # Removes 2 from the set
print(my_set)  # Output: {1, 3, 4}

{1, 3, 4}


#### 4. Set Operations: 
  Sets support mathematical operations like:
- Union (|): Combines elements from both sets.
- Intersection (&): Includes only elements common to both sets.
- Difference (-): Includes elements in one set but not in another.
- Symmetric Difference (^): Elements in either set but not in both.

##### example:

If A = {1, 2, 3} and B = {3, 4, 5},
A | B results in {1, 2, 3, 4, 5} (union),  
A & B results in {3} (intersection).

#### 5. No Indexing or Slicing: 
   Because sets are unordered, you cannot access elements by index like you would with lists or strings.

#### 6. Efficient Membership Testing: 
   Sets are optimized for fast membership checks using the in keyword, which is more efficient than using lists or tuples.

#### 7. Set Methods: 

##### Example: 
1. add(): Adds an element to the set.
2. remove(): Removes a specific element from the set. Raises an error if the element is not found.
3. discard(): Removes an element if it is present, but does not raise an error if it is absent.
4. pop(): Removes and returns an arbitrary element from the set.
5. clear(): Removes all elements from the set.
6. copy(): Returns a shallow copy of the set.

#### 8. Frozen Sets:
  Python also provides frozenset, an immutable version of a set. Once created, elements cannot be added or removed.

##### Example:

In [81]:
#Creating a set
my_set = {1, 2, 3, 4, 5}
# Adding an element
my_set.add(6)
# Removing an element
my_set.remove(3)
# Performing union
another_set = {4, 5, 6, 7}
union_set = my_set | another_set  # {1, 2, 4, 5, 6, 7}

In [82]:
print(union_set)

{1, 2, 4, 5, 6, 7}


#### Examples of Set Use:

#### 1. Removing Duplicates from a List:  
Sets can be used to filter out duplicates from a collection.

In [83]:
my_list = [1, 2, 2, 3, 4, 4, 5]

In [84]:
unique_elements = set(my_list)

In [85]:
unique_elements

{1, 2, 3, 4, 5}

#### 2.Mathematical Set Operations:
Sets are useful in scenarios where you need to perform union, intersection, or difference operations, such as working with groups or categories.

In [86]:
group_A = {"apple", "banana", "cherry"}
group_B = {"banana", "cherry", "dates"}

In [87]:
common_fruits = group_A & group_B

In [88]:
common_fruits

{'banana', 'cherry'}

#### 3. Fast Membership Testing:  
When dealing with a large dataset, sets are useful for checking whether an element exists quickly.

In [89]:
user_id = 1001
valid_ids = {1001, 1002, 1003}
if user_id in valid_ids:
    print("Valid user")        

Valid user


#### 4. Removing Elements from a Set:  
A set can be used to efficiently keep track of items and remove them once they are no longer needed.

In [90]:
to_do_tasks = {"task1", "task2", "task3"}
to_do_tasks.remove("task2")  

In [91]:
to_do_tasks

{'task1', 'task3'}

### Que 6.  Discuss the use cases o tuples and sets in Python programming.

Tuples and sets are both important data structures in Python, each with distinct characteristics and use cases:

#### Tuples Characteristics:


##### 1.Immutable: 
Once a tuple is created, its elements cannot be modified, added, or removed. This makes tuples useful when you need a collection of items that should not change.

##### 2.Ordered: 
Tuples maintain the order of elements, so the order in which items are added is the order in which they are stored.

##### 3.Indexable: 
You can access elements of a tuple using indexing, similar to lists.

##### 4.Hashble:
Because tuples are immutable, they can be used as keys in dictionaries.

#### Use Cases:

##### 1.Fixed Collections: 
Tuples are ideal for storing a fixed collection of items that shouldn't change, such as coordinates (x, y), RGB color values, or configurations.

##### 2.Function Returns:
When a function needs to return multiple values, tuples provide a simple way to return them as a single object.

##### 3.Dictionary Keys:
Since tuples are immutable, they can be used as keys in dictionaries, especially when you need a composite key.

##### 4.Data Integrity:
When you want to ensure that the data stored in a collection remains constant, tuples are the go-to choice.

##### Example:

In [92]:
coordinates = (10, 20)
rgb_color = (255, 0, 0)

In [93]:
point = (2, 3)

In [94]:
dictionary = {point: "This is a point"}

#### Sets Characteristics:


##### 1.Mutable (but elements must be immutable):
You can add or remove elements from a set, but all elements must be immutable (e.g., numbers, strings, tuples).

##### 2.Unordered: 
Sets do not maintain any specific order of elements.

##### 3.No Duplicates: 
Sets automatically discard duplicate entries, making them useful for operations where uniqueness is required.

##### 4.Efficient Membership Testing:
Sets are optimized for checking if an item is part of the set.

#### Use Cases:

##### 1.Removing Duplicates: 
Sets are perfect for eliminating duplicate values from a collection, such as a list of items where you only need unique elements.

##### 2.Membership Testing: 
Sets allow for fast membership tests, which is useful when you need to check whether an element exists in a collection.

##### 3.Set Operations: 
You can perform mathematical set operations like union, intersection, difference, and symmetric difference, which are helpful in various computational tasks.

##### 4.Unordered Collections: 
When the order of elements doesn’t matter and you only care about uniqueness, sets are an ideal choice.

##### Example:

In [95]:
fruits = {"apple", "banana", "cherry", "apple"}  # "apple" is stored only once
unique_numbers = set([1, 2, 3, 1, 4, 4])  # duplicates removed
if "banana" in fruits:
    print("Banana is in the set")

# Set operations
a = {1, 2, 3}
b = {3, 4, 5}
print(a & b)  # Intersection
print(a | b)  # Union
print(a - b)  # Difference

Banana is in the set
{3}
{1, 2, 3, 4, 5}
{1, 2}


#### Summary:

Tuples are best used when you need an ordered and immutable collection.

Sets are useful for storing unique, unordered elements and performing set operations efficiently.

### Que 7: Describe how to add, modify and delete items in a dictionary with examples.

In Python, dictionaries are mutable data structures that allow you to store key-value pairs. You can easily add, modify, and delete items in a dictionary. Here's how you can do it with examples:

Adding Items to a Dictionary
To add an item to a dictionary, you simply assign a value to a new key.

In [96]:
# Create an empty dictionary
my_dict = {}

# Add a key-value pair
my_dict['name'] = 'Alice'
my_dict['age'] = 30

# Add another key-value pair
my_dict['city'] = 'New York'

In [97]:
print(my_dict)

{'name': 'Alice', 'age': 30, 'city': 'New York'}


Modifying Items in a Dictionary
To modify an existing item, you can assign a new value to an existing key.

In [98]:
# Modify the value associated with the key 'age'
my_dict['age'] = 31

# Modify the value associated with the key 'city'
my_dict['city'] = 'Los Angeles'

In [99]:
print(my_dict)

{'name': 'Alice', 'age': 31, 'city': 'Los Angeles'}


Deleting Items from a Dictionary
You can delete items from a dictionary using the del statement, pop() method, or popitem() method.

##### 1.Using del to remove a specific key-value pair:

In [100]:
# Delete the key-value pair with the key 'city'
del my_dict['city']

In [101]:
print(my_dict)

{'name': 'Alice', 'age': 31}


##### 2.Using pop() to remove a key-value pair and return the value:

In [102]:
# Remove the key-value pair with the key 'age' and return its value
age = my_dict.pop('age')

print(my_dict)  # 'age' is now removed
print(age)      # The removed value (31) is returned


{'name': 'Alice'}
31


##### 3.Using popitem() to remove the last inserted key-value pair (in Python 3.7+):

In [103]:
# Add some more key-value pairs
my_dict['country'] = 'USA'
my_dict['job'] = 'Engineer'

# Remove and return the last inserted key-value pair
last_item = my_dict.popitem()

print(my_dict)  # The last inserted key-value pair is removed
print(last_item) # The removed pair is returned as a tuple


{'name': 'Alice', 'country': 'USA'}
('job', 'Engineer')


#### Summary

##### Adding: 
Use my_dict[key] = value to add a new key-value pair.

##### Modifying: 
Use my_dict[key] = new_value to update the value associated with an existing key.

##### Deleting: 
Use del my_dict[key], my_dict.pop(key), or my_dict.popitem() to remove items from the dictionary.

### Que 8.  Discuss the importance of dictionary keys being immutable and provde examples.

In Python, dictionary keys must be immutable. This immutability requirement is crucial for the efficient and correct functioning of dictionaries, particularly because dictionaries are implemented using hash tables. Here’s why immutable keys are important, along with examples:

##### Why Dictionary Keys Must Be Immutable

#### 1.Hashability:
Python dictionaries use a hash table to store key-value pairs. When a key is added to a dictionary, Python computes the hash of the key to determine where to store the associated value.
Mutable objects, such as lists or dictionaries themselves, can change after their creation, leading to inconsistencies in their hash values. If the hash value changes after the key has been placed in the dictionary, it would become impossible to reliably locate the associated value.

#### 2.Consistency and Reliability:
If dictionary keys were mutable, they could be changed after being added to the dictionary. This could lead to unpredictable behavior, where the key-value pair might become unreachable or even lost within the dictionary, leading to potential bugs and data integrity issues.

#### 3.Performance:
Immutability ensures that the hashing process is consistent and quick. Since the hash value of an immutable object remains constant, lookups, insertions, and deletions in a dictionary are performed efficiently.

Examples of Immutable and Mutable Types
                                                                                                                                          
#### Immutable types (can be dictionary keys):

int, float, str, tuple, frozenset

#### Mutable types (cannot be dictionary keys):

list, dict, set
##### Example 1: 
##### Using Immutable Keys

In [104]:
# Using an immutable type (string) as a dictionary key
my_dict = {
    'name': 'Alice',
    'age': 30
}

# Using an immutable tuple as a key
location = (40.7128, -74.0060)  # Tuple representing coordinates (latitude, longitude)
my_dict[location] = 'New York City'

print(my_dict)

{'name': 'Alice', 'age': 30, (40.7128, -74.006): 'New York City'}


Here, the string 'name' and the tuple (40.7128, -74.0060) are both immutable and therefore valid dictionary keys.

##### Example 2: 
##### Attempting to Use a Mutable Key

In [105]:
# Trying to use a list as a dictionary key (This will raise an error)
my_dict = {}
key = [1, 2, 3]

# This will raise a TypeError
try:
    my_dict[key] = 'value'
except TypeError as e:
    print(f"Error: {e}")

Error: unhashable type: 'list'


Here, using a list as a dictionary key raises a TypeError because lists are mutable and cannot be hashed.

##### Example 3: 
##### Mutability Impact on Hashability

In [106]:
# Example of using a tuple (immutable) as a key
my_dict = {}
key = (1, 2, 3)
my_dict[key] = 'Tuple Key'

# Now trying with a mutable version of the key (list inside the tuple)
mutable_key = (1, 2, [3])

# This will raise a TypeError because the list inside the tuple is mutable
try:
    my_dict[mutable_key] = 'Invalid Key'
except TypeError as e:
    print(f"Error: {e}")


Error: unhashable type: 'list'


Even though tuples are generally immutable, a tuple containing a mutable element (like a list) is not hashable, thus cannot be used as a dictionary key.

#### Summary

Dictionary keys must be immutable to ensure that their hash value remains consistent throughout the lifetime of the dictionary entry.

Immutable keys allow dictionaries to perform fast and reliable lookups.

Attempting to use a mutable object as a dictionary key will result in a TypeError because mutable objects can change, which would break the consistency and integrity of the dictionary.